var data = [{
  'genre': 'Acción',
  'name': 'EL PASAJERO',
  'image': '../assets/images/portada01.jpg',
  'Actors': 'Liam Neeson, Vera Farmiga',
  'censorship': 'Mayores 14 años',
  'synopsis': 'Durante su trayecto habitual de vuelta a casa en tren, un hombre de negocios, de pronto entabla conversación con una misteriosa pasajera.Pronto el hombre se verá envuelto en una conspiración criminal que amenaza con poner en peligro tanto su vida como la de sus seres más cercanos.',
},
{
  'genre': 'Ciencia Ficción',
  'name': 'JUMANJI',
  'image': '../assets/images/portada02.jpg',
  'Actors': 'Dwayne Johnson, Kevin Hart, Jack Black, Karen Gillan ',
  'censorship': 'Apta para todos',
  'synopsis': 'Remake de la película homónima de 1995 adaptado a la época actual, en donde cuatro adolescentes se introducen en un nueva aventura a partir de "Jumanji", un videojuego que sirve como un portal a través del espacio-tiempo. Absorbidos por el mundo de Jumanji, este juego no se puede abandonar hasta que acaba la partida.',
},
{
  'genre': 'Drama Musical',
  'name': 'EL GRAN SHOWMAN',
  'image': '../assets/images/portada03.jpg',
  'Actors': 'Zac Efron, Hugh Jackman, Zendaya, Michelle Williams',
  'censorship': 'Mayores 14 años',
  'synopsis': 'Es un original musical que celebra el origen del mundo del espectáculo y la capacidad de asombro que sentimos cuando los sueños cobran vida. Inspirada en la ambición e imaginación de P.T. Barnum, “El Gran Showman” cuenta la historia de un visionario que surgió de la nada para crear un espectáculo fascinante, que se convirtió en un éxito mundial.',
},
{
  'genre': 'Comedia',
  'name': 'EL GRAN LEÓN',
  'image': '../assets/images/portada04.jpg',
  'Actors': ' Gianella Neyra, Carlos Alcántara, Christian Rivero ',
  'censorship': 'Apta para todos',
  'synopsis': 'Ivana Cornejo, es una abogada divorciada y socia de su ex marido Diego en un estudio jurídico. Después de perder su celular recibe una llamada de León Godoy, quien encontró el teléfono y tiene la intención de devolvérselo. En la conversación telefónica se establece una gran empatía y ambos sienten un inmediato interés, por lo que coordinan encontrarse. El “problema” es que León mide 1,36 metros, por lo cual, a partir de ese encuentro, Ivana intenta superar esos centímetros que le faltan al hombre de su vida, enfrentando los prejuicios sociales y los propios.',
},
{
  'genre': 'Terror',
  'name': 'EL REGRESO DEL DEMONIO 3',
  'image': '../assets/images/portada05.jpg',
  'Actors': ' Meg Foster, Gabrielle Haugh, Stan Shaw, Brandon Smith, Chester Rushing',
  'censorship': 'Mayores 14 años',
  'synopsis': 'Trish Jenner es ahora madre de un adolescente llamado Darry, en memoria del hermano que Trish perdió 23 años atrás. La mujer tiene la pesadilla recurrente de que su hijo tendrá el mismo destino a manos de “The Creeper”. Pero a diferencia de entonces ahora es rica y poderosa, y tratará de impedirlo. Por su parte Gaylen Brandon es una excéntrica y dotada Médium que lidera una tropa de sargentos, entre ellos Chris Brandon y Davis Tubbs con el fin de detener a la temible criatura de una vez por todas y salvar a Addi Brandon,  también capturada por The Creeper. Así todos se acercan más que nunca a aprender los secretos de sus oscuros orígenes, ya que el terror aterroriza a la comunidad agrícola local.',
},
{
  'genre': 'Animación-Aventura',
  'name': 'COCO',
  'image': '../assets/images/portada06.png',
  'Actors': 'Gael García Berna',
  'censorship': 'Mayores 14 años',
  'synopsis': 'A pesar de la incomprensible prohibición de la música desde hace varias generaciones en su familia, Miguel sueña con convertirse en un músico consagrado, como su ídolo Ernesto de la Cruz. Desesperado por probar su talento, Miguel se encuentra en la impresionante y colorida Tierra de los Muertos como resultado de una misteriosa cadena de eventos. En el camino, encuentra al simpático timador Héctor, y juntos se embarcan en una extraordinaria travesía para develar la verdadera razón detrás de la historia familiar de Miguel.',
}];
